from typing import Any, Protocol

from src.memory.types import MessageRecord


class MessageRepositoryProtocol(Protocol):
    async def save(
        self,
        session_id: str,
        role: str,
        content: str | None,
        model: str | None = None,
        tool_call_id: str | None = None,
        tool_calls: str | None = None,
        reasoning: str = "",
        phases: str = "[]",
        prompt_tokens: int = 0,
        completion_tokens: int = 0,
        total_tokens: int = 0,
    ) -> None: ...

    async def save_record(self, record: MessageRecord) -> None: ...

    async def get_session_messages(self, session_id: str, limit: int = 500) -> list[tuple[Any, ...]]: ...

    async def delete_empty_assistant(self, session_id: str) -> None: ...

    async def delete_by_session(self, session_id: str, cursor: Any = None) -> None: ...


class SessionRepositoryProtocol(Protocol):
    async def ensure(self, session_id: str, *, origin_node_id: str = "") -> None: ...

    async def exists(self, session_id: str) -> bool: ...

    async def rename(self, session_id: str, name: str) -> None: ...

    async def delete(self, session_id: str, cursor: Any = None) -> None: ...

    async def delete_cascade(self, session_id: str, repos: Any) -> None: ...

    async def get_all(self, limit: int = 50) -> list[tuple[Any, ...]]: ...

    async def check_should_rename(self, session_id: str) -> bool: ...


class ToolCallRepositoryProtocol(Protocol):
    async def log(self, session_id: str, tool_name: str, input_str: str, status: str, turn: int = 0) -> None: ...

    async def record_execution(
        self,
        session_id: str,
        tool_name: str,
        input_str: str,
        status: str,
        tool_result: str,
        turn: int = 0,
        tool_call_id: str | None = None,
    ) -> None: ...

    async def get_history(self, session_id: str, limit: int = 10) -> list[tuple[Any, ...]]: ...

    async def delete_by_session(self, session_id: str, cursor: Any = None) -> None: ...


class WidgetStateRepositoryProtocol(Protocol):
    async def save_state(self, session_id: str, widget_id: str, state: str) -> None: ...

    async def get_states(self, session_id: str) -> dict[str, str]: ...

    async def delete_by_session(self, session_id: str, cursor: Any = None) -> None: ...


class DebugRepositoryProtocol(Protocol):
    async def save_info(self, session_id: str, data: dict[str, Any]) -> None: ...

    async def get_info(self, session_id: str) -> dict[str, Any]: ...

    async def delete_by_session(self, session_id: str, cursor: Any = None) -> None: ...


class SavedWidgetRepositoryProtocol(Protocol):
    async def save(self, session_id: str, widget_id: str, code: str, description: str = "") -> dict[str, Any]: ...

    async def delete_by_session(self, session_id: str, cursor: Any = None) -> None: ...

    async def get(self, widget_id: str) -> dict[str, Any] | None: ...

    async def get_versions(self, widget_id: str) -> list[dict[str, Any]]: ...

    async def get_by_version(self, widget_id: str, version: int) -> dict[str, Any] | None: ...


class MemoryIndexRepositoryProtocol(Protocol):
    async def upsert(self, session_id: str, key: str, value: str) -> None: ...

    async def get(self, session_id: str, key: str) -> str | None: ...

    async def get_all(self, session_id: str) -> list[dict[str, str]]: ...

    async def delete(self, session_id: str, key: str) -> None: ...

    async def delete_by_session(self, session_id: str, cursor: Any = None) -> None: ...
